export class Routes {
  static readonly MAIN = 'pages/MainPage'
  static readonly HOME = 'pages/HomePage'
  static readonly STATS = 'pages/StatsPage'
  static readonly ACHIEVEMENT = 'pages/AchievementPage'
  static readonly ONBOARDING = 'pages/OnboardingPage'
  static readonly RECORD_DETAIL = 'pages/RecordDetailPage'
  static readonly BEVERAGE = 'pages/BeveragePage'
  static readonly GOAL_SETTINGS = 'pages/GoalSettingsPage'
  static readonly PROFILE = 'pages/ProfilePage'
  static readonly PLANT_GARDEN = 'pages/PlantGardenPage'
  static readonly DATA_MANAGE = 'pages/DataManagePage'
}
